### ISSUE TITLE
10.3 Prueba de la Clase Producto

### ISSUE THREAD

**Issue by NataliaLiscio1985** [CodeSystem2022/Binary-Brains_Tercer-Semestre#125]
Correspondiente a la clase 10 JS de LABORATORIO III

**Comment by TamaraPiccinni** [comment]
Archivo de SistemaVentas JS desde la linea 33 a la 38

**Comment by Carolina-Riddick** [comment]
Cambios realizado y subidos en Prueba de la Clase Producto de Javascript
